version: 2 # Version of CircleCI

          
jobs:
  build:
    context: My_var 
    docker:
      - image: cimg/base:stable
    steps:
      - checkout

      - run:
          name: Build Docker image
          environment:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
          command: |
            echo ${DOCKER_USERNAME}