version: 2 # Version of CircleCI
jobs:
  build:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker
      - run:
        # installs a docker client that will be used to run the docker commands
        name: Install Docker client
        command: |
          set -x VER="17.03.0-ce"
          curl -L -o /tmp/docker-$VER.tgz https://get.docker.com/builds/Linux/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          sudo mv /tmp/docker/* /usr/bin
      - run:
        name: Build Docker image
        command: |
          docker build -t reverseproxy ./udagram-reverseproxy
          docker build -t udagram-api-user ./udagram-api-user
          docker build -t udagram-api-feed ./udagram-api-feed
          docker build -t udagram-frontend ./udagram-frontend
      
      - run:
        name: taging
        command: |
          docker tag reverseproxy zyadhany/reverseproxy:v1
          docker tag udagram-api-user zyadhany/udagram-api-user:v1
          docker tag udagram-api-feed zyadhany/udagram-api-feed:v1
          docker tag udagram-frontend:latest zyadhany/udagram-front:v1

      
      - run:
        name: Push to Docker Hub
        command: |
          docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
          docker push zyadhany/reverseproxy:v1
          docker push zyadhany/udagram-api-user:v1
          docker push zyadhany/udagram-api-feed:v1
          docker push zyadhany/udagram-front:v1