version: 2 # Version of CircleCI

          
jobs:
  build:
    context: My_var 
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - setup_remote_docker 
      - run:
          name: Install Docker Compose
          environment:
            COMPOSE_VERSION: '1.29.2'
          command: |
            curl -L "https://github.com/docker/compose/releases/download/${COMPOSE_VERSION}/docker-compose-$(uname -s)-$(uname -m)" -o ~/docker-compose
            chmod +x ~/docker-compose
            sudo mv ~/docker-compose /usr/local/bin/docker-compose

      - run:
          name: Build Docker image
          environment:
            username: $DOCKER_USERNAME
            password: $DOCKER_PASSWORD
          command: |
            echo $DOCKER_USERNAME